MANO:
  ROOT: MANO
  USE_PCA: False
  FLAT_HAND_MEAN: True
  SIDE: right

MODEL:
  BACKBONE: dinov2_vitl14_reg
  DECODER_LAYERS: 6
  DECODER_HEADS: 8
  DROPOUT: 0.0
  AGG_DIM: 256
  AGG_LAYERS: 2
  TS_LAYERS: 2
  TS_WINDOW: 4
  T_CONTEXT: 8

TRAIN:
  LR: 1.0e-4
  WEIGHT_DECAY: 1.0e-4
  BATCH_SIZE: 8
  MAX_EPOCHS: 100
  LOSS_JOINTS3D: 300.0
  LOSS_JOINTS2D: 300.0
  LOSS_POSE: 60.0
  LOSS_TRANS: 60.0
  LOSS_OBJ_POS: 10.0
  LOSS_OBJ_ROT: 10.0
  LOSS_COARSE: 0.5
